hosts:
  stage:  # demo host
    hostname: 127.0.0.1
    remote_user: user
    database_user: db_user
    labels:
      type: feature-branch-deployment
    deploy_path: /var/www/html/
    public_urls:
      - https://demo.local/
