<?php

namespace Deployer;


task('dev:release:npm_update', function () {
    if (in_array('dev:release:npm_update', get('disabled_tasks'))) { return; }
    info("npm update");
    runLocally("npx npm-check-updates --target=semver --upgrade --prefix " . get('npm_path_app') . " >> _tmp.txt 2>&1");
    // @ToDo: why is the complete output not be generated by the runLocally command, only getting the last 500 chars, so need to perform this workaround to collection dependency information
    $result = runLocally("cat _tmp.txt");
    runLocally("rm -f _tmp.txt");
    $message = get("dev_git_message_npm_update") . "\n\n";

    preg_match_all(get('dev_npm_regex'), $result, $matches);
    foreach ($matches[1] as $index => $package) {
        $message .= " - $package (" . $matches[2][$index] . " => " . $matches[3][$index] . ")\n";
    }

    info("commit updates");
    runLocally("git add .");
    runLocally("git commit --no-verify -m \"$message\"");
})->desc('Update npm dependencies');